id: AA07D9EDD
base_file: f133C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:05:44.894182
  last_modified_at: 2022-06-17 14:05:44.894195
